var banaPrice =12;
console.log( typeof banaPrice);
var isHot =true;
console.log(isHot);
var name ="My name is miraz";
console.log( typeof name);
const userName =21;
console.log(userName);
var mirazName ="I have bike YOU DONt mind";
console.log(mirazName.toLowerCase());
var malihaName ="miraz is a unsmart boy in this big world";
console.log(malihaName.toUpperCase());
var stild ="i am miraz";
console.log(stild.split(' '));
var still ="i am miraz";
console.log(still.indexOf('miraz'));
var number1 ="20.5";
var number2 =50;
number1 = parseInt(number1);
console.log(number1 + number2);
var number3 ="22.5";
var number4 =52;
number3 = parseFloat(number3);
console.log(number3 + number4);
var number5 ="25.5";
var number6 =55;
number5 = +number5;
console.log(number5 + number6);
var numberall1 =0.1;
var numberall2 =0.2;
var total = numberall1 + numberall2;
total = ''+total;
console.log( typeof total);
var numberall3 =0.1;
var numberall4 =0.2;
var totall = numberall3 + numberall4;
totall =totall.toFixed(1);
console.log(totall);
var mumer =23;
var mumer2 =20;
var result =mumer / mumer2;
console.log(result);
var 